'use client'

import { useMemo, useState } from 'react'
import { BarChart3, Bell, BookOpen, CalendarDays, Check, ChevronRight, Clock3, FileText, Flame, GraduationCap, HelpCircle, LayoutDashboard, Lightbulb, ListChecks, Menu, MessageCircle, Moon, MoreHorizontal, Play, Plus, Search, Settings, Sparkles, Target, Timer, TrendingUp, Upload, Users, X, Zap } from 'lucide-react'
import { Avatar, AvatarFallback } from '@/components/ui/avatar'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Progress } from '@/components/ui/progress'
import { Separator } from '@/components/ui/separator'
import { Textarea } from '@/components/ui/textarea'

const nav = [
  { label: 'Overview', icon: LayoutDashboard }, { label: 'My Study Plan', icon: ListChecks }, { label: 'Calendar', icon: CalendarDays }, { label: 'Progress Analytics', icon: BarChart3 }, { label: 'Subjects & Topics', icon: BookOpen },
]
const workspace = [
  { label: 'AI Tutor', icon: MessageCircle }, { label: 'Quiz Center', icon: HelpCircle }, { label: 'Upload Materials', icon: Upload }, { label: 'Study Session', icon: Timer }, { label: 'Deadlines', icon: Target },
]
const days = ['MON','TUE','WED','THU','FRI','SAT','SUN']
const bars = [58, 72, 48, 82, 66, 88, 74, 92, 70, 84, 62, 78]

export default function Page() {
  const [active, setActive] = useState('Overview')
  const [dark, setDark] = useState(true)
  const [tasks, setTasks] = useState(['Vectors & planes', 'Organic chemistry review', 'Spanish flashcards'])
  const [chat, setChat] = useState('')
  const [messages, setMessages] = useState([{ from: 'ai', text: 'Hey Alex. I noticed you have a gap in thermodynamics. Want a 5-minute refresher before your physics block?' }])
  const [timer, setTimer] = useState(false)
  const [uploaded, setUploaded] = useState(false)

  const completion = useMemo(() => Math.min(100, 68 + (3 - tasks.length) * 6), [tasks.length])
  const pageTitle = active === 'Overview' ? 'Good morning, Alex' : active

  function completeTask(task: string) {
    setTasks((current) => current.filter((item) => item !== task))
  }
  function sendMessage() {
    if (!chat.trim()) return
    setMessages((current) => [...current, { from: 'user', text: chat }, { from: 'ai', text: 'I built a focused micro-lesson around that. Start with the worked example, then test yourself with two retrieval questions.' }])
    setChat('')
  }

  return <div className={dark ? 'app-shell dark' : 'app-shell'}>
    <aside className="sidebar">
      <div className="brand"><div className="brand-mark"><Sparkles size={17} /></div><span>nexora</span><Badge variant="secondary">BETA</Badge></div>
      <div className="profile-mini"><Avatar><AvatarFallback>AS</AvatarFallback></Avatar><div><strong>Alex Stone</strong><span>Computer Science</span></div><MoreHorizontal size={17} /></div>
      <nav className="side-nav"><p className="eyebrow">Workspace</p>{nav.map(({ label, icon: Icon }) => <button key={label} onClick={() => setActive(label)} className={active === label ? 'nav-item active' : 'nav-item'}><Icon size={17} /><span>{label}</span>{label === 'Overview' && <span className="live-dot" />}</button>)}<p className="eyebrow second">Tools</p>{workspace.map(({ label, icon: Icon }) => <button key={label} onClick={() => setActive(label)} className={active === label ? 'nav-item active' : 'nav-item'}><Icon size={17} /><span>{label}</span>{label === 'AI Tutor' && <Badge className="nav-badge">AI</Badge>}</button>)}</nav>
      <div className="sidebar-bottom"><div className="upgrade-card"><Zap size={18}/><div><strong>Unlock your full potential</strong><span>Get deeper insights with Pro</span></div><ChevronRight size={16}/></div><button className="nav-item" onClick={() => setActive('Settings')}><Settings size={17}/><span>Settings</span></button><button className="nav-item" onClick={() => setDark(!dark)}>{dark ? <Moon size={17}/> : <Sparkles size={17}/>}<span>{dark ? 'Dark mode' : 'Light mode'}</span><span className="switch-on" /></button></div>
    </aside>
    <main className="main-content">
      <header className="topbar"><button className="mobile-menu"><Menu size={20}/></button><div className="breadcrumbs"><span>Workspace</span><ChevronRight size={14}/><strong>{active}</strong></div><div className="top-actions"><div className="search"><Search size={16}/><Input placeholder="Search anything..." /></div><Button variant="ghost" size="icon" aria-label="Notifications"><Bell size={18}/><i /></Button><Avatar className="top-avatar"><AvatarFallback>AS</AvatarFallback></Avatar></div></header>
      <div className="content-wrap">
        <div className="page-heading"><div><p className="eyebrow accent">THURSDAY, OCTOBER 24, 2024</p><h1>{pageTitle}</h1><p className="subhead">Your adaptive plan is tuned and ready. Let&apos;s make today count.</p></div><div className="heading-actions"><Button variant="outline" onClick={() => setActive('Calendar')}><CalendarDays data-icon="inline-start"/> View calendar</Button><Button onClick={() => setTimer(!timer)}><Play data-icon="inline-start"/> {timer ? 'Session active' : 'Start session'}</Button></div></div>
        {active === 'Overview' ? <Dashboard tasks={tasks} completion={completion} onComplete={completeTask} timer={timer} setActive={setActive} uploaded={uploaded} setUploaded={setUploaded} /> : <SectionView active={active} tasks={tasks} setActive={setActive} messages={messages} chat={chat} setChat={setChat} sendMessage={sendMessage} uploaded={uploaded} setUploaded={setUploaded} timer={timer} setTimer={setTimer} />}
      </div>
    </main>
  </div>
}

function Dashboard({ tasks, completion, onComplete, timer, setActive, uploaded, setUploaded }: any) {
  return <div className="dashboard-grid">
    <section className="hero-card"><div className="hero-copy"><Badge className="ai-pill"><Sparkles data-icon="inline-start"/> AI ADAPTIVE PLAN</Badge><h2>Your path to <em>mastery</em><br/>is taking shape.</h2><p>Nexora has rebalanced your week based on your recent quiz results and available study time.</p><Button onClick={() => setActive('My Study Plan')}>View my study plan <ChevronRight data-icon="inline-end"/></Button></div><div className="hero-visual"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="mastery-ring"><strong>{completion}%</strong><span>overall progress</span></div><div className="float-chip chip-one"><TrendingUp size={14}/> +12% this week</div><div className="float-chip chip-two"><Check size={14}/> On track</div></div></section>
    <div className="stats-row"><StatCard icon={<Target/>} label="Mastery score" value="74%" delta="+8.4%" color="cyan"/><StatCard icon={<Flame/>} label="Study streak" value="12 days" delta="Personal best" color="orange"/><StatCard icon={<Clock3/>} label="Focus time" value="8h 42m" delta="This week" color="purple"/><StatCard icon={<GraduationCap/>} label="Exam countdown" value="23 days" delta="Calculus II" color="green"/></div>
    <section className="wide-card today-card"><CardHeader><div><CardTitle>What should I study now?</CardTitle><CardDescription>Your highest-impact next step, based on your goals.</CardDescription></div><Badge variant="outline" className="priority"><Zap size={13}/> High impact</Badge></CardHeader><CardContent><div className="recommendation"><div className="rec-icon"><Lightbulb size={22}/></div><div className="rec-main"><div className="rec-label">RECOMMENDED MICRO-LESSON · 25 MIN</div><h3>Thermodynamics: Entropy &amp; spontaneity</h3><p>Strengthen a weak concept before it becomes a gap. You&apos;re 64% confident here.</p><div className="rec-meta"><span><BookOpen size={14}/> Physics 201</span><span><Clock3 size={14}/> 25 min</span><span><Target size={14}/> +14 mastery</span></div></div><Button onClick={() => setActive('Study Session')}><Play data-icon="inline-start"/> Start now</Button></div></CardContent></section>
    <section className="wide-card plan-card"><CardHeader><div><CardTitle>Today&apos;s study plan</CardTitle><CardDescription>Thursday · 3h 15m planned <span className="green-text">· 68% complete</span></CardDescription></div><Button variant="ghost" size="sm" onClick={() => setActive('My Study Plan')}>See full plan <ChevronRight data-icon="inline-end"/></Button></CardHeader><CardContent><div className="timeline">{tasks.map((task: string, index: number) => <div className="timeline-item" key={task}><div className={index === 0 ? 'timeline-dot current' : 'timeline-dot'}>{index === 0 && <span/>}</div><div className="task-time">{index === 0 ? '10:00 AM' : index === 1 ? '1:30 PM' : '4:00 PM'}<span>{index === 0 ? '25 min' : index === 1 ? '45 min' : '20 min'}</span></div><div className="task-detail"><strong>{task}</strong><span>{index === 0 ? 'Micro-lesson · Recommended' : index === 1 ? 'Active recall · Chemistry' : 'Spaced repetition · Language'}</span></div><button className="complete-btn" onClick={() => onComplete(task)} aria-label={`Complete ${task}`}><Check size={15}/></button></div>)}{tasks.length === 0 && <div className="empty-row"><Check size={18}/> Nice work — today&apos;s plan is complete.</div>}</div></CardContent></section>
    <section className="chart-card"><CardHeader><div><CardTitle>Progress snapshot</CardTitle><CardDescription>Mastery points · Last 12 weeks</CardDescription></div><Button variant="ghost" size="icon" onClick={() => setActive('Progress Analytics')}><MoreHorizontal/></Button></CardHeader><CardContent><div className="chart-value"><strong>74.2</strong><span className="green-text">+8.4%</span></div><div className="bar-chart">{bars.map((height, i) => <div className="bar-wrap" key={i}><div className={i === 7 ? 'bar selected' : 'bar'} style={{ height: `${height}%` }}/>{i % 2 === 0 && <span>{i === 0 ? 'Aug 1' : i === 4 ? 'Sep 1' : i === 8 ? 'Oct 1' : ''}</span>}</div>)}</div></CardContent></section>
    <section className="risk-card"><CardHeader><div><CardTitle>Skill gap bridge</CardTitle><CardDescription>Concepts worth revisiting</CardDescription></div><Badge variant="secondary">3 gaps</Badge></CardHeader><CardContent><div className="gap-list"><GapItem title="Entropy & spontaneity" subject="Physics 201" score="64%" width="64%"/><GapItem title="Integration by parts" subject="Calculus II" score="58%" width="58%"/><GapItem title="Cellular respiration" subject="Biology" score="71%" width="71%"/></div><Button variant="outline" className="full-btn" onClick={() => setActive('Subjects & Topics')}>Explore skill gaps <ChevronRight data-icon="inline-end"/></Button></CardContent></section>
    <section className="wide-card deadline-card"><CardHeader><div><CardTitle>Upcoming deadlines</CardTitle><CardDescription>Stay ahead of what&apos;s next</CardDescription></div><Button variant="ghost" size="sm" onClick={() => setActive('Deadlines')}>View all <ChevronRight data-icon="inline-end"/></Button></CardHeader><CardContent><div className="deadlines"><Deadline date="OCT 28" title="Calculus II midterm" subject="Calculus II" urgent/><Deadline date="NOV 02" title="Physics lab report" subject="Physics 201"/><Deadline date="NOV 08" title="Spanish oral presentation" subject="Spanish 204"/></div></CardContent></section>
    <section className="wide-card tutor-card"><div className="tutor-orb"><MessageCircle size={23}/></div><div><Badge className="ai-pill">AI TUTOR</Badge><h3>Need a little momentum?</h3><p>Ask me anything about your current subjects. I&apos;m context-aware and ready to help.</p></div><Button variant="outline" onClick={() => setActive('AI Tutor')}>Open tutor <ChevronRight data-icon="inline-end"/></Button></section>
  </div>
}
function StatCard({ icon, label, value, delta, color }: any) { return <Card className={`stat-card stat-${color}`}><CardContent><div className="stat-icon">{icon}</div><div><span>{label}</span><strong>{value}</strong><small>{delta}</small></div></CardContent></Card> }
function GapItem({ title, subject, score, width }: any) { return <div className="gap-item"><div><strong>{title}</strong><span>{subject}</span></div><div className="gap-score"><span>{score}</span><Progress value={Number.parseInt(width)} /></div></div> }
function Deadline({ date, title, subject, urgent }: any) { return <div className="deadline"><div className={urgent ? 'date urgent' : 'date'}>{date}</div><div><strong>{title}</strong><span>{subject}</span></div><ChevronRight size={16}/></div> }

function SectionView({ active, tasks, setActive, messages, chat, setChat, sendMessage, uploaded, setUploaded, timer, setTimer }: any) {
  if (active === 'AI Tutor') return <section className="section-panel tutor-panel"><div className="section-intro"><Badge className="ai-pill"><Sparkles data-icon="inline-start"/> CONTEXT-AWARE</Badge><h2>Your AI study partner</h2><p>Ask questions, get unstuck, and turn confusion into confidence.</p></div><div className="chat-window"><div className="chat-head"><div className="ai-avatar"><Sparkles size={17}/></div><div><strong>Nexora Tutor</strong><span>Online · Knows your study plan</span></div><Badge variant="outline">Physics 201 context</Badge></div><div className="chat-messages">{messages.map((message: any, index: number) => <div className={message.from === 'user' ? 'message user' : 'message'} key={index}><div className="message-avatar">{message.from === 'user' ? 'AS' : <Sparkles size={14}/>}</div><p>{message.text}</p></div>)}</div><div className="chat-compose"><Textarea value={chat} onChange={(e) => setChat(e.target.value)} placeholder="Ask about entropy, your plan, or anything you&apos;re learning..." onKeyDown={(e) => { if (e.key === 'Enter' && !e.shiftKey && !e.nativeEvent.isComposing && e.keyCode !== 229) { e.preventDefault(); sendMessage() }}}/><Button onClick={sendMessage}><ChevronRight/></Button></div></div></section>
  return <section className="section-panel"><div className="section-intro"><Badge variant="outline">WORKSPACE</Badge><h2>{active}</h2><p>{sectionCopy[active] || 'Tune your learning experience and keep every goal moving forward.'}</p></div>{active === 'Upload Materials' ? <UploadPanel uploaded={uploaded} setUploaded={setUploaded}/> : active === 'Study Session' ? <SessionPanel timer={timer} setTimer={setTimer}/> : active === 'Calendar' ? <CalendarPanel/> : active === 'Quiz Center' ? <QuizPanel/> : active === 'Progress Analytics' ? <AnalyticsPanel/> : <GenericPanel active={active} tasks={tasks} setActive={setActive}/>}</section>
}
const sectionCopy: Record<string,string> = {'My Study Plan':'Your adaptive timeline updates as you learn, miss sessions, and change priorities.','Calendar':'See the full rhythm of your week and make room for what matters.','Progress Analytics':'Patterns, predictions, and the small wins that compound into mastery.','Subjects & Topics':'Build your curriculum, inspect prerequisites, and close skill gaps.','Quiz Center':'Generate concept checks that reveal what you actually know.','Deadlines':'All your exams, assignments, and risk alerts in one place.','Settings':'Shape Nexora around the way you learn best.'}
function UploadPanel({ uploaded, setUploaded }: any) { return <div className="upload-layout"><Card className="upload-drop"><CardContent><div className="upload-icon"><Upload/></div><h3>{uploaded ? 'Material analyzed' : 'Drop your materials here'}</h3><p>{uploaded ? 'Physics-notes.pdf · 12 concepts extracted · Ready to add to your plan' : 'PDF, DOCX, or a link. Nexora will extract concepts and build your study path.'}</p><Button onClick={() => setUploaded(true)}>{uploaded ? 'View extracted topics' : 'Choose a file'} <Upload data-icon="inline-end"/></Button><span className="upload-note">Maximum file size 25 MB</span></CardContent></Card><Card><CardHeader><CardTitle>Analysis pipeline</CardTitle><CardDescription>From material to mastery</CardDescription></CardHeader><CardContent><div className="pipeline"><div className="pipe active"><Check/><div><strong>Upload material</strong><span>PDF, DOCX, or URL</span></div></div><div className="pipe active"><Sparkles/><div><strong>AI extracts concepts</strong><span>Identifies prerequisites and gaps</span></div></div><div className={uploaded ? 'pipe active' : 'pipe'}><Target/><div><strong>Adaptive plan updated</strong><span>New sessions appear in your timeline</span></div></div></div></CardContent></Card></div>}
function SessionPanel({ timer, setTimer }: any) { return <div className="session-layout"><Card className="timer-card"><CardContent><p className="eyebrow accent">FOCUS SESSION · PHYSICS 201</p><div className="big-timer">{timer ? '24:38' : '25:00'}</div><span className="timer-caption">Thermodynamics: Entropy &amp; spontaneity</span><div className="timer-actions"><Button onClick={() => setTimer(!timer)}><Play data-icon="inline-start"/> {timer ? 'Pause session' : 'Begin focus'}</Button><Button variant="outline">End session</Button></div></CardContent></Card><Card><CardHeader><CardTitle>Session analytics</CardTitle><CardDescription>Your focus patterns this week</CardDescription></CardHeader><CardContent><div className="session-stat"><span>Average focus</span><strong>42 min</strong></div><div className="session-stat"><span>Deep work ratio</span><strong>78%</strong></div><div className="session-stat"><span>Best time of day</span><strong>10–12 AM</strong></div></CardContent></Card></div>}
function CalendarPanel() { return <Card className="calendar-panel"><CardHeader><div><CardTitle>October 2024</CardTitle><CardDescription>3 assignments · 1 exam this month</CardDescription></div><div><Button variant="outline" size="sm">Today</Button><Button variant="ghost" size="icon"><ChevronRight/></Button></div></CardHeader><CardContent><div className="calendar-grid">{days.map(day => <div className="cal-day-label" key={day}>{day}</div>)}{Array.from({length:35}, (_, i) => <button className={i === 23 ? 'calendar-day selected' : i === 27 ? 'calendar-day deadline' : 'calendar-day'} key={i}>{i < 4 ? '' : i - 3}{i === 23 && <span/>}{i === 27 && <i/>}</button>)}</div></CardContent></Card>}
function QuizPanel() { const [score, setScore] = useState<number | null>(null); return <div className="quiz-layout"><Card className="quiz-card"><CardHeader><Badge className="ai-pill">AI GENERATED</Badge><CardTitle>Entropy &amp; spontaneity</CardTitle><CardDescription>Question 1 of 5 · Physics 201</CardDescription></CardHeader><CardContent><h3>Which statement best describes a spontaneous process?</h3><div className="answers">{['It always happens quickly','It occurs without continuous external energy','It can never be reversed','It has zero entropy change'].map((answer, i) => <button key={answer} onClick={() => setScore(i === 1 ? 100 : 40)} className={score !== null && i === 1 ? 'answer correct' : 'answer'}>{String.fromCharCode(65+i)}<span>{answer}</span>{score !== null && i === 1 && <Check/>}</button>)}</div>{score !== null && <div className="quiz-result"><Check size={17}/> Nice work. Spontaneous means thermodynamically favorable without continuous external input.</div>}</CardContent></Card><Card><CardHeader><CardTitle>Mastery snapshot</CardTitle></CardHeader><CardContent><div className="mastery-score"><strong>{score ?? 74}%</strong><span>Current mastery</span></div><Progress value={score ?? 74}/><Separator/><div className="mini-row"><span>Accuracy</span><strong>82%</strong></div><div className="mini-row"><span>Questions completed</span><strong>18</strong></div></CardContent></Card></div>}
function AnalyticsPanel() { return <div className="analytics-layout"><Card><CardHeader><CardTitle>Mastery trajectory</CardTitle><CardDescription>Projected completion with current pace</CardDescription></CardHeader><CardContent><div className="trajectory"><svg viewBox="0 0 600 170" role="img" aria-label="Mastery trajectory chart"><path d="M0 145 C80 138 100 128 150 132 S240 98 295 110 S375 82 425 76 S520 35 600 20" fill="none" stroke="currentColor" strokeWidth="4"/><path d="M0 145 C80 138 100 128 150 132 S240 98 295 110 S375 82 425 76 S520 35 600 20 V170 H0Z" fill="currentColor" opacity=".08"/></svg><div className="trajectory-labels"><span>Now</span><span>Exam day</span></div></div></CardContent></Card><Card className="prediction"><CardHeader><CardTitle>Progress prediction</CardTitle><CardDescription>At your current pace</CardDescription></CardHeader><CardContent><div className="prediction-number">91<span>%</span></div><p>Likely exam readiness</p><Badge>On track</Badge><Button variant="outline" className="full-btn">Run what-if simulator</Button></CardContent></Card></div>}
function GenericPanel({ active, tasks, setActive }: any) { return <div className="generic-grid"><Card><CardHeader><CardTitle>{active === 'Subjects & Topics' ? 'Curriculum builder' : active === 'My Study Plan' ? 'Adaptive timeline' : 'Your command center'}</CardTitle><CardDescription>Personalized to your goals, pace, and learning preferences.</CardDescription></CardHeader><CardContent><div className="feature-list"><div><div className="list-icon"><Target/></div><span><strong>Learning goals</strong><small>Master Calculus II by November 16</small></span><ChevronRight/></div><div><div className="list-icon"><Zap/></div><span><strong>Preferred pace</strong><small>Focused · 5 sessions per week</small></span><ChevronRight/></div><div><div className="list-icon"><ListChecks/></div><span><strong>Spaced repetition</strong><small>Next review due tomorrow</small></span><ChevronRight/></div></div></CardContent></Card><Card><CardHeader><CardTitle>What-if simulator</CardTitle><CardDescription>See how your plan adapts to change.</CardDescription></CardHeader><CardContent><div className="simulator"><label>Missed study days <span>2 days</span></label><input type="range" defaultValue="2" min="0" max="7"/><label>New assignment added <span>None</span></label><Button onClick={() => setActive('My Study Plan')}>Recalculate plan <Sparkles data-icon="inline-start"/></Button></div></CardContent></Card></div>}
